# Generated by Django 2.2.13 on 2025-02-09 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20250210_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.Issue'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(default='Guest', max_length=100),
        ),
    ]
