# Generated by Django 2.2.13 on 2025-02-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20250210_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vote',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(condition=models.Q(user__isnull=False), fields=('issue', 'user'), name='unique_vote_per_user'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(condition=models.Q(ip_address__isnull=False), fields=('issue', 'ip_address'), name='unique_vote_per_ip'),
        ),
    ]
