# Generated by Django 2.2.13 on 2025-02-13 19:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20250213_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
